In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [7]:
data["Species"] = data["Species"].replace({"Iris-setosa": 1, "Iris-versicolor": 2, "Iris-virginica": 3})

In [8]:
data

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        1
1      2            4.9           3.0            1.4           0.2        1
2      3            4.7           3.2            1.3           0.2        1
3      4            4.6           3.1            1.5           0.2        1
4      5            5.0           3.6            1.4           0.2        1
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        3
146  147            6.3           2.5            5.0           1.9        3
147  148            6.5           3.0            5.2           2.0        3
148  149            6.2           3.4            5.4           2.3        3
149  150            5.9           3.0            5.1           1.8        3

[150 rows x 6 columns]

In [51]:
X_train, X_test, y_train, y_test = train_test_split(data[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]], data["Species"], test_size=0.2)

In [52]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
62             6.0           2.2            4.0           1.0
139            6.9           3.1            5.4           2.1
85             6.0           3.4            4.5           1.6
14             5.8           4.0            1.2           0.2
8              4.4           2.9            1.4           0.2
..             ...           ...            ...           ...
82             5.8           2.7            3.9           1.2
12             4.8           3.0            1.4           0.1
105            7.6           3.0            6.6           2.1
26             5.0           3.4            1.6           0.4
10             5.4           3.7            1.5           0.2

[120 rows x 4 columns]

In [57]:
from sklearn import linear_model
mymodel = linear_model.LogisticRegression(max_iter=120)
mymodel.fit(X_train,y_train)

LogisticRegression(max_iter=120)

In [58]:
mymodel.predict(X_test)

array([2, 2, 1, 2, 1, 1, 1, 3, 3, 2, 1, 1, 1, 1, 1, 3, 2, 1, 3, 2, 3, 2,
       2, 1, 1, 1, 1, 1, 2, 3], dtype=int64)

In [59]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
52             6.9           3.1            4.9           1.5
68             6.2           2.2            4.5           1.5
7              5.0           3.4            1.5           0.2
59             5.2           2.7            3.9           1.4
18             5.7           3.8            1.7           0.3
47             4.6           3.2            1.4           0.2
49             5.0           3.3            1.4           0.2
145            6.7           3.0            5.2           2.3
109            7.2           3.6            6.1           2.5
54             6.5           2.8            4.6           1.5
13             4.3           3.0            1.1           0.1
36             5.5           3.5            1.3           0.2
5              5.4           3.9            1.7           0.4
17             5.1           3.5            1.4           0.3
39             5.1           3.4            1.5           0.2
104            6.5           3.0            5.8           2.2
106            4.9           2.5            4.5           1.7
11             4.8           3.4            1.6           0.2
149            5.9           3.0            5.1           1.8
64             5.6           2.9            3.6           1.3
130            7.4           2.8            6.1           1.9
91             6.1           3.0            4.6           1.4
96             5.7           2.9            4.2           1.3
35             5.0           3.2            1.2           0.2
16             5.4           3.9            1.3           0.4
46             5.1           3.8            1.6           0.2
6              4.6           3.4            1.4           0.3
34             4.9           3.1            1.5           0.1
50             7.0           3.2            4.7           1.4
100            6.3           3.3            6.0           2.5

In [60]:
mymodel.score(X_test, y_test)

0.9666666666666667

In [63]:
predicted_output = mymodel.predict(X_test)
predicted_output

array([2, 2, 1, 2, 1, 1, 1, 3, 3, 2, 1, 1, 1, 1, 1, 3, 2, 1, 3, 2, 3, 2,
       2, 1, 1, 1, 1, 1, 2, 3], dtype=int64)

In [64]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicted_output)
cm

array([[15,  0,  0],
       [ 0,  8,  0],
       [ 0,  1,  6]], dtype=int64)